// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Xcaciv.LoaderTests")]

[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.LoadFromPath(System.String,System.String,System.Boolean)~Xcaciv.Loader.IAssemblyContext")]
[assembly: SuppressMessage("Trimming", "IL2072:Target parameter argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The return value of the source method does not have matching annotations.", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.CreateInstance(System.String)~System.Object")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.CreateInstance(System.String)~System.Object")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.CreateInstance``1(System.String)~``0")]
[assembly: SuppressMessage("Trimming", "IL2046:'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.GetVersion~System.Version")]
[assembly: SuppressMessage("Trimming", "IL2072:Target parameter argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The return value of the source method does not have matching annotations.", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.CreateInstance``1(System.String)~``0")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.CreateInstance``1(System.String)~``0")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.LoadContext_Resolving(System.Runtime.Loader.AssemblyLoadContext,System.Reflection.AssemblyName)~System.Reflection.Assembly")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.loadAssembly~System.Reflection.Assembly")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.GetTypes~System.Collections.Generic.IEnumerable{System.Type}")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.GetTypes(System.Type)~System.Collections.Generic.IEnumerable{System.Type}")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Purpose of class is to load unrefrenced code.", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.GetTypes``1~System.Collections.Generic.IEnumerable{System.Type}")]
[assembly: SuppressMessage("Trimming", "IL2067:Target parameter argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method. The parameter of method does not have matching annotations.", Justification = "<Pending>", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.ActivateInstance``1(System.Type)~``0")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Dynamic assembly loading is intrinsic to this library", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.GetLoadedTypes``1~System.Collections.Generic.IEnumerable{System.Type}")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Dynamic assembly loading is intrinsic to this library", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.LoadFromPath~System.Reflection.Assembly")]
[assembly: SuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "Dynamic assembly loading is intrinsic to this library", Scope = "member", Target = "~M:Xcaciv.Loader.AssemblyContext.LoadFromPath(System.Runtime.Loader.AssemblyLoadContext,System.String)~System.Reflection.Assembly")]
